# REDIS
redis:
  host: 42.192.15.218 #localhost #
  port: 6379
  client-type: lettuce
  lettuce:
    pool:
      max-active: 8

  # REDIS
  redis:
    host: localhost # 42.192.15.218 #localhost #
    port: 6379
    client-type: lettuce
    lettuce:
      pool:
        max-active: 8